age=c(20,15,18,19)
height=c(5.1,5.2,5.5,5.7)
weight=c(20,45,65,70)
gender=c("male","female","male","female")
df=data.frame(age,height,weight,gender)
print(df)
paste("ages are: ")
print(df$age)
summary(df$age)
 summary(is.factor(df$age))