b=matrix(c(1:9),nrow=3,byrow=TRUE)
print(b)
a=matrix(c(1:9),nrow=3,byrow=TRUE)
print(b)
paste("matrix additon is")
print(a+b)
paste("matrix subtraction is")
print(a-b)
paste("matrix divison is")
print(a/b)
paste("matrix multipication is")
print(a*b)